src/app/layout/datasets/datasets.component.html, src/app/layout/datasets/datasets.component.ts, src/app/layout/datasets/openlayermap/controls/olmap.layers.component.ts, src/app/layout/datasets/record.modal.component.html, yarn.lock
Displaying  legal information correctly from the NCI MT data CSW records
https://jira.csiro.au/browse/DEVL-56
=> Devl 56 mt data legal

src/app/layout/components/sidebar/sidebar.component.ts, src/app/layout/jobs/jobs.component.html, src/app/layout/jobs/jobs.component.ts, src/app/layout/jobs/jobs.service.ts, src/app/layout/jobs/preview/image-preview.component.html, src/app/layout/jobs/preview/image-preview.component.ts, src/app/layout/jobs/preview/log-preview.component.html, src/app/layout/jobs/preview/log-preview.component.ts, src/app/layout/user/user-management.component.ts, src/app/shared/modules/vgl/vgl.service.ts
* Fixed image preview.
* Log files will now display.
* Any file extension that isn't recognised will be attempted to be previewed as plain text.
https://jira.csiro.au/browse/DEVL-67
https://jira.csiro.au/browse/DEVL-68
=> DEVL 67 and 68 - Fix image and log preview

.vscode/settings.json, src/app/layout/datasets/confirm-datasets.modal.component.html, src/app/layout/datasets/confirm-datasets.modal.component.ts, src/app/layout/datasets/datasets-display.component.html, src/app/layout/datasets/datasets-display.component.scss, src/app/layout/datasets/datasets-display.component.spec.ts, src/app/layout/datasets/datasets-display.component.ts, src/app/layout/datasets/datasets.component.html, src/app/layout/datasets/datasets.component.ts, src/app/layout/datasets/datasets.module.ts, src/app/layout/datasets/download-options.modal.component.html, src/app/layout/datasets/download-options.modal.component.ts, src/app/layout/datasets/openlayermap/controls/olmap.select.data.component.ts, src/app/shared/modules/vgl/models.ts, src/app/shared/modules/vgl/vgl.service.ts, src/app/shared/services/auth.service.ts, src/app/shared/services/csw-search.service.ts, src/app/shared/services/user-state.service.ts
https://jira.csiro.au/browse/DEVL-55
=> Devl 55 bookmark

.gitignore, package.json, src/app/layout/jobs/job-browser.component.html, src/app/layout/jobs/job-browser.component.ts, src/app/layout/jobs/job-inputs.component.html, src/app/layout/jobs/jobs.component.html, src/app/layout/jobs/jobs.component.scss, src/app/layout/jobs/jobs.module.ts, src/app/layout/layout.component.scss, yarn.lock
Added split panels to job monitor page. Tested in Firefox and Chrome and seemed to work. All a bit fragile as it seems very hard to get elements to fill their parent height. Feel free to suggest improvements.
=> Devl 71 job monitor splitview

src/app/app.module.ts, src/app/layout/layout-routing.module.ts
changed empty path in layout module
=> fixed route in layout module on user login

src/app/layout/jobs/jobs.component.html, src/app/layout/jobs/jobs.component.ts, src/app/layout/jobs/jobs.module.ts, src/app/layout/jobs/jobs.service.ts, src/app/layout/jobs/preview/image-preview.component.html, src/app/layout/jobs/preview/image-preview.component.scss, src/app/layout/jobs/preview/image-preview.component.ts, src/app/layout/jobs/preview/log-preview.component.html, src/app/layout/jobs/preview/log-preview.component.scss, src/app/layout/jobs/preview/log-preview.component.ts, src/app/shared/modules/vgl/vgl.service.ts, yarn.lock
https://jira.csiro.au/browse/DEVL-68
=> Devl 68 fix broken previews

src/app/shared/modules/vgl/vgl.service.ts
A minor addition to job submission to ensure script templates are encoded safely (and don't bust the URL size limit) by POSTing the request. Also using POST for the download updates.
Added explicit vgl{Get,Post} methods to vgl.service that handle query/form encoding for convenience.
=> POST templates and downloads for size and encoding safety

src/app/layout/jobs/job-browser.component.html, src/app/layout/jobs/job-browser.component.ts, src/app/layout/jobs/jobs.component.ts, src/app/layout/jobs/jobs.module.ts, src/app/layout/jobs/jobs.service.ts, src/app/shared/modules/vgl/vgl.service.ts, yarn.lock
https://jira.csiro.au/browse/DEVL-73
- Added drag and drop feature to job browser.
- Added p-toast to handle error message while deleting job/series
- Changed refresh of job browser to refresh of status of the jobs displayed every 60 secs
- fixed the issues mentioned in the task. https://jira.csiro.au/browse/DEVL-73
- added functionality to move jobs to top level
=> Devl 73 changes

src/app/shared/services/auth.service.ts
If check fails User will be redirected to the Profile screen and asked to accept. If they have already accepted they'll be redirected as normal.
=> T&C's acceptance will be confirmed after User login

src/app/layout/job-wizard/job-solutions-summary.component.html, src/app/layout/job-wizard/job-solutions-summary.component.ts, src/app/shared/services/user-state.service.ts
fixed bugs as per https://jira.csiro.au/browse/DEVL-72
=> made changes as per jira task DEVL-72

src/app/layout/jobs/jobs.component.ts, src/app/layout/jobs/jobs.module.ts, src/app/layout/jobs/preview/plaintext-preview.component.html, src/app/layout/jobs/preview/plaintext-preview.component.ts, src/app/layout/jobs/preview/preview-item.ts, src/app/shared/modules/vgl/models.ts
Prettier file previews for text files (particularly code files). Matches Solutions code view.
https://jira.csiro.au/browse/DEVL-88
=> Added ngx-monaco-editor to plain text previewer

src/app/layout/datasets/confirm-datasets.modal.component.ts, src/app/layout/datasets/datasets.module.ts, src/app/layout/datasets/openlayermap/controls/olmap.select.data.component.ts, src/app/layout/datasets/record.modal.component.html, src/app/layout/datasets/record.modal.component.scss, src/app/layout/datasets/record.modal.component.ts, src/app/layout/datasets/remote-datasets.modal.component.html, src/app/layout/datasets/remote-datasets.modal.component.scss, src/app/layout/datasets/remote-datasets.modal.component.spec.ts, src/app/layout/datasets/remote-datasets.modal.component.ts, src/app/layout/jobs/job-browser.component.html, src/app/layout/jobs/job-browser.component.ts, src/app/layout/jobs/jobs.component.html, src/app/layout/jobs/submission/job-submission-datasets.component.html, src/app/layout/jobs/submission/job-submission-datasets.component.scss, src/app/layout/jobs/submission/job-submission-datasets.component.ts, src/app/shared/modules/vgl/models.ts, src/app/shared/services/csw-search.service.ts, yarn.lock
Also PrimeNG version update and CSS change.
https://jira.csiro.au/browse/DEVL-101
Have added default values for fields, and some general tidying of code.
=> Devl 85 capture non layer datasets

src/app/app-routing.module.ts, src/app/layout/components/sidebar/sidebar.component.ts, src/app/layout/datasets/datasets-display.component.html, src/app/layout/datasets/datasets-display.component.scss, src/app/layout/datasets/datasets.component.html, src/app/layout/datasets/datasets.component.scss, src/app/layout/datasets/datasets.component.ts, src/app/layout/datasets/datasets.module.ts, src/app/layout/datasets/openlayermap/controls/olmap.layers.component.html, src/app/layout/datasets/openlayermap/controls/olmap.select.data.component.html, src/app/layout/datasets/openlayermap/controls/olmap.zoom.component.html, src/app/layout/datasets/openlayermap/olmap.component.ts, src/app/layout/layout.component.scss
Refer to Jira task for changes made:
https://jira.csiro.au/browse/DEVL-106
=> Datasets page tweaks:

src/app/layout/components/header/header.component.html, src/app/layout/components/sidebar/sidebar.component.html, src/app/layout/datasets/confirm-datasets.modal.component.html, src/app/layout/datasets/confirm-datasets.modal.component.ts, src/app/layout/datasets/record.modal.component.html, src/app/layout/datasets/remote-datasets.modal.component.html, src/app/layout/jobs/submission/job-submission-datasets.component.html
Also:
* Lots of button made primary for consistency.
* Create Job button added to Capture Datasets dialog.
* Unused options removed from User menu.
=> New Job button out of Header, into Sidebar.

src/app/layout/jobs/job-browser.component.html, src/app/layout/jobs/job-browser.component.ts, src/app/layout/jobs/jobs.component.html, src/app/layout/jobs/jobs.component.ts, src/app/layout/jobs/jobs.service.ts, src/app/shared/modules/vgl/vgl.service.ts
https://jira.csiro.au/browse/DEVL-104
https://jira.csiro.au/browse/DEVL-107
Context menu was sticking around (e.g. right-click, then left click another node, original node still highlighted). Required custom sort function that now allows us to sort over multiple columns (hold CTRL when sorting a column).
Plus a bunch more minor UI tweaks, button classes, error messages etc.
=> Devl 104 107 job context menu and delete

src/app/layout/user/user-management.component.html, yarn.lock
Replaced kitten by short instructions and created wiki page with detailed instructions for the embedded link.
=> Fixes DEVL-99: AWS Setup insturctions

src/app/layout/datasets/download-options.modal.component.html, src/app/layout/datasets/download-options.modal.component.scss, src/app/layout/datasets/record.modal.component.html, src/app/layout/datasets/remote-datasets.modal.component.scss, src/app/layout/job-wizard/job-datasets.component.html, src/app/layout/job-wizard/job-object.component.scss, src/app/layout/job-wizard/job-solutions-summary.component.html, src/app/layout/job-wizard/job-wizard.component.html, src/app/layout/jobs/job-browser.component.html, src/app/layout/jobs/job-inputs.component.html, src/app/layout/jobs/job-status.modal.component.html, src/app/layout/jobs/jobs.component.html, src/app/layout/solutions/solutions-detail.component.html, src/app/layout/solutions/solutions.component.html, src/app/layout/user/user-management.component.scss
* Majority of buttons made "btn btn-primary" class for consistency.
* A little bit of space added between buttons where needed for legibility.
* Required asterisks made relative to fix potential scrolling out of container issues.
* Job monitor page tweaks, now always displays border at bottom on job inputs, which also now has a vertical scrollbar.
=> DEVL - Minor UI tweaks

src/app/layout/job-wizard/job-datasets.component.html, src/app/layout/job-wizard/job-object.component.html, src/app/layout/job-wizard/job-object.component.ts, src/app/layout/job-wizard/job-solutions-summary.component.html, src/app/layout/job-wizard/job-wizard.component.html, src/app/layout/job-wizard/job-wizard.component.ts
1. made changes to enable/disable submit button 
2. fixed a minor bug occurring when saving in job wizard without data and compute provider
3. put space between buttons
=> Job wizard submit button

src/app/layout/components/header/header.component.html, src/app/layout/components/header/header.component.ts, src/app/layout/solutions/solutions-browser/solutions-browser.component.html, src/app/layout/solutions/solutions-browser/solutions-browser.component.scss, src/app/layout/solutions/solutions-browser/solutions-browser.component.ts, src/app/layout/solutions/solutions.component.html, src/app/shared/modules/vgl/vgl.service.ts, src/app/shared/services/auth.service.ts, src/app/shared/services/user-state.service.ts, src/environments/environment.ts, yarn.lock
Fixes:
* Anonymous users won't have a "Logout" option in the User menu when the app first loads.
* Solutions page will display a link to the User Profile page if no services have been configured (and hence no Problems can be displayed).
* Other minor refactoring to improve code.
=> Devl login improvements

src/app/shared/modules/vgl/vgl.service.ts
Added support for NCI Gadi and removed support for retired NCI Raijin.
Require pull request https://github.com/AuScope/ANVGL-Portal/pull/175 on ANVGL-Portal to work
=> Changed Raijin to Gadi

src/app/layout/job-wizard/job-object.component.html, src/app/layout/job-wizard/job-object.component.ts, src/app/shared/modules/vgl/vgl.service.ts
Fixes Aus 3326 and various other issues of the job wizard UI not updating correctly.
Requires corresponding pull request in VGL-Portal.
=> Aus 3326 vgl offers aws compute provider even if solution does not support it

src/app/landingpage/landingpage.component.html, src/app/layout/dashboard/dashboard.component.html, src/app/layout/datasets/datasets-record/datasets-record.component.html, src/app/layout/datasets/datasets-record/datasets-record.component.ts, src/app/layout/datasets/datasets.component.html
* Changed show/hide layer icons for GSKY records
* Disabled ability to bookmark child layers due to no easy way to achieve this without significant code refactoring.
=> Change gsky layer icons

src/app/layout/datasets/datasets-record/datasets-record.component.html, src/app/layout/datasets/datasets-record/datasets-record.component.ts, src/app/layout/datasets/datasets.component.html, src/app/layout/datasets/datasets.component.ts, src/app/shared/modules/vgl/vgl.service.ts, src/app/shared/services/auth.service.ts, yarn.lock
WMS layers with time support added to the map can have time dimension queried and different time periods displayed.
Fixes:
* Datasets tab no longer appears empty if user has bookmarks tab selected before logging out.
* Bookmark duplication on login no longer occurs.
=> WMS time support

src/app/layout/job-wizard/job-object.component.html, src/app/layout/job-wizard/job-object.component.ts, src/app/layout/job-wizard/job-solutions-summary.component.ts, src/app/layout/job-wizard/job-wizard.component.html, src/app/layout/job-wizard/job-wizard.component.ts, src/app/shared/modules/solutions/models.ts, src/app/shared/services/user-state.service.ts, src/environments/environment.ts
Fixed a number of (mostly) UI issues with Job Creation page:
* Submit button now enables when all mandatory fields present (and at least 1 Solution).
* Comboboxes set to correct values on Job load.
* Walltime is checked on load if Job was saved with walltime.
* Removed default Grace URL from environment file.
=> AUS-3462: Job creation page UI issues.

src/app/layout/job-wizard/job-solution-vars.component.ts, yarn.lock
Fix small issue with input file solution var bindings being reset when incorrect array filter fails.
=> Input file binding fix

src/app/layout/jobs/job-inputs.component.html, src/app/layout/jobs/job-inputs.component.ts, src/app/layout/jobs/jobs.service.ts, src/app/shared/modules/vgl/models.ts, src/app/shared/modules/vgl/vgl.service.ts
Job output now displayed in a tree table so folders in the cloud output directory can be browsed.
=> INSAR-46 Job Output Folders
